name: Europe Weather

on:
  workflow_dispatch:

jobs:
  weather:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install packages
      run: |
        pip install openpyxl

    - name: Run weather
      run: |
        python europe_weather.py
